.TH fstring 1 LOCAL
.SH NAME
fstring - find text strings in a directory
.SH SYNOPSIS
.B fstring directory string
.SH AVAILABILITY
Unknown. So far works on Crunchbang Statler 64
.SH DESCRIPTION
search a directory for a string, output filenames and context
.PP usage: fstring /tmp/whatever mysearch
.PP example: fstring ./ hello (search current directory for string "hello"
.SH INSTALLATION
wget https://raw.github.com/figital/fstring/master/fstring
.br
sudo cp fstring /usr/local/bin
.SH OPTIONS
Currently thre are no options
.SH AUTHOR
figital <scott@figital.com>
